pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=typesafe-cla-validator
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
    actions:
      merge:
        method: merge


  - name: Merge ScalaSteward's PRs that are ready
    conditions:
      - author=scala-steward
      - status-success=Travis CI - Pull Request
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
    actions:
      merge:
        method: merge

  - name: backport patches to 1.1.x branch
    conditions:
      - merged
      - label=status:needs-backport
    actions:
      backport:
        branches:
          - 1.1.x
      label:
        remove: [status:needs-backport]

  - name: forward patches to master branch
    conditions:
      - merged
      - label=status:needs-forwardport
    actions:
      backport:
        branches:
          - master
      label:
        remove: [status:needs-forwardport]

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
