version: ~> 1.0
language: scala

before_install:
  - |
    curl -Ls https://git.io/sbt -o sbt || travis_terminate 1
    chmod 0755 sbt || travis_terminate 1
    sudo mv sbt /usr/local/bin/sbt || travis_terminate 1
  - curl --version # for debug purpose
  - if [ ! -f ~/.jabba/jabba.sh ]; then curl -L -v --retry 5 -o jabba-install.sh https://git.io/jabba && bash jabba-install.sh; fi
  - . ~/.jabba/jabba.sh
install: jabba install $(jabba ls-remote "adopt@~1.$TRAVIS_JDK.0-0" --latest=patch) && jabba use "$_" && java -Xmx32m -version

git:
  depth: false # Avoid sbt-dynver not seeing the tag

jobs:
  include:
    - stage: test
      name: "Validations"
      script: sbt headerCheckAll scalafmtCheckAll scalafmtSbtCheck scalastyle mimaReportBinaryIssues
      env:
        - TRAVIS_JDK=11

    - name: "Run tests on AdoptOpenJDK 11"
      script: sbt +test
      env:
        - TRAVIS_JDK=11

    - name: "Run tests on AdoptOpenJDK 8"
      script: sbt +test
      env:
        - TRAVIS_JDK=8

# TODO: replace with Sonatype
#    - stage: publish
#      name: "Publish artifacts to Bintray"
#      script: sbt +publish
#      env:
#        - TRAVIS_JDK=11

stages:
  - name: test
  - name: publish
    if: ((branch = main AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.jabba/jdk"
    - "$HOME/.sbt"
    - "$HOME/.cache/coursier"

before_cache:
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

branches:
  only:
    - main
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
